-- Агуулахын хадгалалтын хураамж
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "storageFee" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "storageFreeDays" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "storageFeePerDay" INTEGER NOT NULL DEFAULT 1000;
