ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "leasingSmsDueToday" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "leasingSmsOverdue" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "leasingSmsArrivedUnpaid" TEXT NOT NULL DEFAULT '';
